server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    
spring:
  datasource:
    url: jdbc:ucanaccess://src/main/resources/accountsdb.accdb;openExclusive=false;ignoreCase=true
    driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
#  mvc:
#   view:
#     prefix: /resources/static/
#     suffix: .html
#     
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  file: ./logs/app.log

  